const getters = {
    //新增
    wordcloudConfig: state => state.common.wordcloudConfig,
    otherCloud: state => state.common.otherCloud,
    cloudCount: state => state.common.cloudCount,
    isOpenCloud: state => state.common.isOpenCloud,
    avueConfig: state => state.common.avueConfig,
    reqloading: state => state.exclude.reqloading,
    imageDomin: state => state.system.imageDomin,
    permissionToken: state => state.user.permissionToken,
    userInfo: state => state.user.userInfo,
    permissions: state => state.user.permissions,
    menus: state => state.user.menus,
    usersList: state => state.user.usersList,
    permissionButton: state => state.user.permissionButton,
    currentMenuModel: state => state.user.currentMenuModel,
    currentMenuModelId: state => state.user.currentMenuModelId,
    articleContent: state => state.user.articleContent,
    topMenus: state => state.user.topMenus,
    modelOptions: state => state.user.modelOptions,
    isMenuRefresh: state => state.exclude.isMenuRefresh,
    //  系统自带
    tag: state => state.tags.tag,
    website: state => state.common.website,
    theme: state => state.common.theme,
    themeName: state => state.common.themeName,
    isShade: state => state.common.isShade,
    isCollapse: state => state.common.isCollapse,
    keyCollapse: (state, getters) => getters.screen > 1 ? getters.isCollapse : false,
    screen: state => state.common.screen,
    isLock: state => state.common.isLock,
    isFullScren: state => state.common.isFullScren,
    lockPasswd: state => state.common.lockPasswd,
    tagList: state => state.tags.tagList,
    tagWel: state => state.tags.tagWel,
    logsList: state => state.logs.logsList,
    logsLen: state => state.logs.logsList.length || 0,
    logsFlag: (state, getters) => getters.logsLen === 0
}
export default getters
